import "./globals.css";

export const metadata = {
  title: "Restaurant",
  description: "Generated by create next app",
  icons: "",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body
      >
        {children}
      </body>
    </html>
  );
}
